### ISSUE TITLE
update to pouch 5

### ISSUE THREAD

**Issue by robertkowalski** [neojski/visualizeRevTree#15]
hi!

thanks to your refactoring last year we were able to reuse parts of visualize rev tree.

we built a conflict solving helper with it (see https://blog.couchdb.org/2016/04/26/databases-arent-boring/)

we are going to use node 6 in our builds, but for that we need a new pouch version. 

is there anything against updating the pouch dep to 5? 

maybe we can make pouch a dev-dependency and people can update pouch / use pouch in the version they prefer?

**Comment by neojski** [comment]
The only reason it's not updated to new pouchdb is that I didn't have time to work on it. Feel free to submit a Pull Request!

**Comment by robertkowalski** [comment]
here we go: https://github.com/neojski/visualizeRevTree/pull/16 :)

**Comment by neojski** [comment]
Thanks!
