### ISSUE TITLE
Cant visualise deleted doc

### ISSUE THREAD

**Issue by daleharvey** [neojski/visualizeRevTree#5]
If I do a bunch of stuff then delete a document, would like to still be able to see its rev tree

**Comment by neojski** [comment]
I think that we can change [this `if`](https://github.com/neojski/visualizeRevTree/blob/8e107eb74766734fd29adddec8edf01ed688e925/visualizeRevTree.js#L83) into `if (err != document got deleted)` and it should work

**Comment by neojski** [comment]
Would you please confirm @daleharvey that it's fixed?

**Comment by daleharvey** [comment]
Yup working great - http://neojski.github.io/visualizeRevTree/?url=http%3A%2F%2Fcouchdb.pouchdb.com%2Ftest%2Funique

Cheers
