### ISSUE TITLE
Visualizer does not respect port number

### ISSUE THREAD

**Issue by neojski** [neojski/visualizeRevTree#9]
If you type `http://localhost:2020/xxx/yyy` it does not work (it works like with `5984`)

**Comment by daleharvey** [comment]
Ah sorry I took a guess and got the wrong one, if you replaced url.hostname with url.host it would do the right thing as well, but thats pretty much the same as this

**Comment by neojski** [comment]
https://github.com/neojski/visualizeRevTree/commit/8b8bb67355ab0df51a5c847ff1bf2e581f5fd1b8 :-)
